name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - Guru99Insurance_with_Report

jobs:
  build:
    runs-on: ubuntu-latest  # Change if using a self-hosted runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven  # Automatically caches dependencies

      # Step 3: Cache Maven dependencies (Optional, handled above)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # Step 4: Install dependencies and run tests
      - name: Build and test with Maven
        run: mvn clean verify

      # Step 5: Archive Test Results (Fixed version)
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4  # ✅ Updated version
        with:
          name: test-results
          path: target/surefire-reports/

      # Step 6: Store Reports (Fixed version)
      - name: Archive Extent/Allure Reports
        if: always()
        uses: actions/upload-artifact@v4  # ✅ Updated version
        with:
          name: test-reports
          path: target/reports/  # Adjust the path based on your framework
