name: Selenium Tests

on:
  push:
    branches:
      - main
      - Guru99Insurance_with_Report
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean install

      # Run Selenium tests
      - name: Run Selenium Tests
        run: mvn test

      # Archive test reports
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/

      # Send email with test results
      - name: Send email with test results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Test Results
          body: |
            Selenium tests have completed. Please find the attached test report.
          to: your-email@example.com
          from: GitHub Actions <your-email@example.com>
          attachments: target/surefire-reports/
